apiVersion: v1
kind: Service
metadata:
  name: javaproject-service
spec:
  type: NodePort
  selector:
    app: javaproject
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008  # NodePort between 30000-32767